
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweeter_clone_development
  
test:
  <<: *default
  database: tweeter_clone_test

production:
  <<: *default
  database: tweeter_clone_production
  username: tweeter_clone
  password: <%= ENV['TWEETER_CLONE_DATABASE_PASSWORD'] %>
